package oracle.apps.per.sample.server.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface EmployeesVORow extends Row {
    Date getDateOfBirth();

    Date getEffectiveEndDate();

    Date getEffectiveStartDate();

    String getEmployeeNumber();

    String getMaritalStatus();

    Number getPersonId();

    void setDateOfBirth(Date value);

    void setEffectiveEndDate(Date value);

    void setEffectiveStartDate(Date value);

    void setEmployeeNumber(String value);

    void setMaritalStatus(String value);

    void setPersonId(Number value);
}
