package oracle.apps.per.sample.server.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesVORowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public EmployeesVORowClient() {
    }


    public Date getDateOfBirth() {
        return (Date)getAttribute("DateOfBirth");
    }

    public Date getEffectiveEndDate() {
        return (Date)getAttribute("EffectiveEndDate");
    }

    public Date getEffectiveStartDate() {
        return (Date)getAttribute("EffectiveStartDate");
    }

    public String getEmployeeNumber() {
        return (String)getAttribute("EmployeeNumber");
    }

    public String getMaritalStatus() {
        return (String)getAttribute("MaritalStatus");
    }

    public Number getPersonId() {
        return (Number)getAttribute("PersonId");
    }

    public void setDateOfBirth(Date value) {
        setAttribute("DateOfBirth", value);
    }

    public void setEffectiveEndDate(Date value) {
        setAttribute("EffectiveEndDate", value);
    }

    public void setEffectiveStartDate(Date value) {
        setAttribute("EffectiveStartDate", value);
    }

    public void setEmployeeNumber(String value) {
        setAttribute("EmployeeNumber", value);
    }

    public void setMaritalStatus(String value) {
        setAttribute("MaritalStatus", value);
    }

    public void setPersonId(Number value) {
        setAttribute("PersonId", value);
    }
}
