package oracle.apps.per.sample.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.apps.per.sample.server.common.EmployeesVORow;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesVORowImpl extends OAViewRowImpl implements EmployeesVORow {
    public static final int PERSONID = 0;
    public static final int EFFECTIVESTARTDATE = 1;
    public static final int EFFECTIVEENDDATE = 2;
    public static final int EMPLOYEENUMBER = 3;
    public static final int MARITALSTATUS = 4;
    public static final int DATEOFBIRTH = 5;

    /**This is the default constructor (do not remove)
     */
    public EmployeesVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute PersonId
     */
    public Number getPersonId() {
        return (Number) getAttributeInternal(PERSONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PersonId
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**Gets the attribute value for the calculated attribute EffectiveStartDate
     */
    public Date getEffectiveStartDate() {
        return (Date) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EffectiveStartDate
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**Gets the attribute value for the calculated attribute EffectiveEndDate
     */
    public Date getEffectiveEndDate() {
        return (Date) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EffectiveEndDate
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**Gets the attribute value for the calculated attribute EmployeeNumber
     */
    public String getEmployeeNumber() {
        return (String) getAttributeInternal(EMPLOYEENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeeNumber
     */
    public void setEmployeeNumber(String value) {
        setAttributeInternal(EMPLOYEENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute MaritalStatus
     */
    public String getMaritalStatus() {
        return (String) getAttributeInternal(MARITALSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MaritalStatus
     */
    public void setMaritalStatus(String value) {
        setAttributeInternal(MARITALSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute DateOfBirth
     */
    public Date getDateOfBirth() {
        return (Date) getAttributeInternal(DATEOFBIRTH);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DateOfBirth
     */
    public void setDateOfBirth(Date value) {
        setAttributeInternal(DATEOFBIRTH, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERSONID:
            return getPersonId();
        case EFFECTIVESTARTDATE:
            return getEffectiveStartDate();
        case EFFECTIVEENDDATE:
            return getEffectiveEndDate();
        case EMPLOYEENUMBER:
            return getEmployeeNumber();
        case MARITALSTATUS:
            return getMaritalStatus();
        case DATEOFBIRTH:
            return getDateOfBirth();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERSONID:
            setPersonId((Number)value);
            return;
        case EFFECTIVESTARTDATE:
            setEffectiveStartDate((Date)value);
            return;
        case EFFECTIVEENDDATE:
            setEffectiveEndDate((Date)value);
            return;
        case EMPLOYEENUMBER:
            setEmployeeNumber((String)value);
            return;
        case MARITALSTATUS:
            setMaritalStatus((String)value);
            return;
        case DATEOFBIRTH:
            setDateOfBirth((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
