package oracle.apps.per.sample.server;

import java.util.ArrayList;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;

import oracle.apps.per.sample.beans.Employee;
import oracle.apps.per.sample.beans.EmployeeInfo;

import oracle.jbo.RowSetIterator;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------

/**
 * A sample class to demonstrate how Application Module can use the ISG REST framework. This class provides
 * methods to return Employees
 * @rep:scope public
 * @rep:product PER
 * @rep:displayname Employees
 * @rep:category BUSINESS_ENTITY HR_USER_HOOK
 * @rep:category IREP_CLASS_SUBTYPE AM_SERVICES
 */
public class EmployeesAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public EmployeesAMImpl() {
    }

    public EmployeesVOImpl getEmployeesVO1() {
        return (EmployeesVOImpl)findViewObject("EmployeesVO1");
    }

    /**
     * 
     * This method returns Employee Info
     *
     * @param pEmployeeNumber Employee Number of the Employee
     * @rep:paraminfo {@rep:innertype oracle.apps.per.sample.beans.EmployeeInfo}
     * @return EmployeeInfo
     * @rep:scope public
     * @rep:displayname Get Employees
     * @rep:httpverb get
     */
    public EmployeeInfo getEmployees(String pEmployeeNumber) {
        EmployeeInfo info = new EmployeeInfo();
        ArrayList<Employee> employees = new ArrayList<Employee>();
        EmployeesVOImpl vo = getEmployeesVO1();
        
        if (pEmployeeNumber != null || pEmployeeNumber.length() != 0) {
            vo.setNamedWhereClauseParam("p_employee_number",pEmployeeNumber);
        }
        
        vo.executeQuery();

        RowSetIterator iter = vo.createRowSetIterator(null);
        iter.reset();

        while (iter.hasNext()) {
            EmployeesVORowImpl row = (EmployeesVORowImpl)iter.next();
            Employee emp = new Employee();
            emp.setPersonId(row.getPersonId().intValue());
            emp.setEffectiveStartdate(row.getEffectiveStartDate().dateValue());
            emp.setEffectiveEndDate(row.getEffectiveEndDate().dateValue());
            emp.setEmployeeNumber(row.getEmployeeNumber());
            emp.setMaritalStatus(row.getMaritalStatus());
            emp.setDateOfBirth(row.getDateOfBirth().dateValue());
            employees.add(emp);
        }
        
        iter.closeRowSetIterator();
        info.setEmployees(employees);

        return info;
    }

}
